Table reminders.user_reminder_setting {
  id uuid [pk]
  user_id uuid [not null, unique, ref: > identity.user.id]
  reminder_enabled boolean [not null, default: false]
  created_at timestamptz [not null]
  updated_at timestamptz [not null]
  time_zone text [not null]
}

Table identity.user { id uuid [pk] }
