services:
  main-server:
    build:
      context: .
      dockerfile: src/Dockerfile
    env_file:
      - .env.${NODE_ENV}
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ['sh', '-c', 'npm ci && npm run start:server:watch']
  background-workers:
    build:
      context: .
      dockerfile: workers/Dockerfile
    env_file:
      - .env.${NODE_ENV}
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ['sh', '-c', 'npm ci && npm run start:workers:watch']
  python-service:
    build:
      context: .
      dockerfile: pythonService/Dockerfile
    env_file:
      - .env.${NODE_ENV}
    environment:
      NODE_ENV: ${NODE_ENV}
      ENABLE_DEBUG_WINDOW: '0'
    volumes:
      - ./pythonService/main.py:/app/main.py
      - ./pythonService/config:/app/config
      - ./pythonService/publishers:/app/publishers
      - ./pythonService/services:/app/services
      - ./pythonService/analyzers:/app/analyzers
      - ./pythonService/aws:/app/aws
      - ./pythonService/utils:/app/utils
    command: ['python', 'main.py']
