CREATE SCHEMA "analytics";
--> statement-breakpoint
CREATE SCHEMA "auth";
--> statement-breakpoint
CREATE SCHEMA "identity";
--> statement-breakpoint
CREATE SCHEMA "messages";
--> statement-breakpoint
CREATE SCHEMA "reminders";
--> statement-breakpoint
CREATE SCHEMA "tracking";
--> statement-breakpoint
CREATE SCHEMA "workout";
--> statement-breakpoint
CREATE TYPE "identity"."Auth Providers" AS ENUM('apple', 'google', 'app');--> statement-breakpoint
CREATE ROLE "anon";--> statement-breakpoint
CREATE ROLE "app_user";--> statement-breakpoint
CREATE ROLE "authenticated";--> statement-breakpoint
CREATE ROLE "service_role";--> statement-breakpoint
CREATE OR REPLACE FUNCTION "auth"."uid"()
RETURNS uuid
LANGUAGE sql
STABLE
AS $$
  SELECT nullif(current_setting('app.current_user_id', true), '')::uuid
$$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION "identity"."current_user_id"()
RETURNS uuid
LANGUAGE sql
STABLE
AS $$
  SELECT nullif(current_setting('app.current_user_id', true), '')::uuid
$$;--> statement-breakpoint
CREATE TABLE "identity"."oauth_accounts" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"provider" text NOT NULL,
	"provider_user_id" text NOT NULL,
	"provider_email" text NOT NULL,
	"linked_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc') NOT NULL,
	"missing_fields" text,
	CONSTRAINT "oauth_accounts_pkey" PRIMARY KEY("id"),
	CONSTRAINT "oauth_accounts_provider_user_unique" UNIQUE("provider","provider_user_id")
);
--> statement-breakpoint
ALTER TABLE "identity"."oauth_accounts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "identity"."users" (
	"username" text NOT NULL,
	"email" text NOT NULL,
	"name" text NOT NULL,
	"gender" text DEFAULT 'Unknown' NOT NULL,
	"created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc') NOT NULL,
	"profile_image_url" text,
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"push_token" text,
	"password" text,
	"role" text DEFAULT 'User' NOT NULL,
	"is_first_login" boolean DEFAULT true NOT NULL,
	"token_version" bigint DEFAULT 0 NOT NULL,
	"is_verified" boolean DEFAULT false NOT NULL,
	"auth_provider" text DEFAULT 'app' NOT NULL,
	"last_login" timestamp with time zone,
	CONSTRAINT "users_pkey" PRIMARY KEY("id")
);
--> statement-breakpoint
ALTER TABLE "identity"."users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "messages"."messages" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"sender_id" uuid DEFAULT "identity"."current_user_id"() NOT NULL,
	"receiver_id" uuid DEFAULT "identity"."current_user_id"() NOT NULL,
	"subject" text DEFAULT 'Subject' NOT NULL,
	"msg" text DEFAULT 'Hello World' NOT NULL,
	"sent_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc') NOT NULL,
	"is_read" boolean DEFAULT false NOT NULL,
	CONSTRAINT "messages_pkey" PRIMARY KEY("id")
);
--> statement-breakpoint
ALTER TABLE "messages"."messages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "reminders"."user_reminder_settings" (
	"user_id" uuid NOT NULL,
	"workout_reminders_enabled" boolean DEFAULT true NOT NULL,
	"reminder_offset_minutes" integer DEFAULT 60 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT timezone('UTC', now()) NOT NULL,
	"timezone" text DEFAULT '''UTC''::text',
	CONSTRAINT "user_reminder_settings_pkey" PRIMARY KEY("user_id")
);
--> statement-breakpoint
ALTER TABLE "reminders"."user_reminder_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "reminders"."user_split_information" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "reminders"."user_split_information_id_seq1" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"split_id" bigint NOT NULL,
	"estimated_time_utc" timestamp with time zone NOT NULL,
	"confidence" numeric(3, 2) DEFAULT '1.00' NOT NULL,
	"last_computed_at" timestamp with time zone DEFAULT timezone('UTC', now()) NOT NULL,
	"preferred_weekday" integer,
	CONSTRAINT "user_split_information_pkey" PRIMARY KEY("id"),
	CONSTRAINT "user_split_information_user_id_split_id_key" UNIQUE("user_id","split_id")
);
--> statement-breakpoint
ALTER TABLE "reminders"."user_split_information" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "tracking"."aerobictracking" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "tracking"."aerobictracking_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"type" text NOT NULL,
	"duration_mins" bigint DEFAULT 0 NOT NULL,
	"duration_sec" bigint DEFAULT 0 NOT NULL,
	"workout_time_utc" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc') NOT NULL,
	CONSTRAINT "aerobictracking_pkey" PRIMARY KEY("id")
);
--> statement-breakpoint
ALTER TABLE "tracking"."aerobictracking" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "tracking"."exercisetracking" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "tracking"."exercisetracking_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"exercisetosplit_id" bigint NOT NULL,
	"weight" real[] NOT NULL,
	"reps" bigint[] NOT NULL,
	"notes" text,
	"workout_summary_id" uuid NOT NULL,
	CONSTRAINT "exercisetracking_pkey" PRIMARY KEY("id")
);
--> statement-breakpoint
ALTER TABLE "tracking"."exercisetracking" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "tracking"."workout_summary" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"workout_start_utc" timestamp with time zone NOT NULL,
	"workout_end_utc" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"workoutsplit_id" bigint NOT NULL,
	CONSTRAINT "workout_summary_pkey" PRIMARY KEY("id")
);
--> statement-breakpoint
ALTER TABLE "tracking"."workout_summary" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "workout"."exercises" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "workout"."exercises_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text NOT NULL,
	"targetmuscle" text NOT NULL,
	"specifictargetmuscle" text NOT NULL,
	CONSTRAINT "exercises_pkey" PRIMARY KEY("id")
);
--> statement-breakpoint
ALTER TABLE "workout"."exercises" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "workout"."exercisetoworkoutsplit" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "workout"."ExerciseToWorkoutsplit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"exercise_id" bigint NOT NULL,
	"workoutsplit_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"sets" bigint[] NOT NULL,
	"order_index" bigint NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "ExerciseToWorkoutsplit_pkey" PRIMARY KEY("id"),
	CONSTRAINT "uq_ets_split_exercise" UNIQUE("workoutsplit_id","exercise_id")
);
--> statement-breakpoint
ALTER TABLE "workout"."exercisetoworkoutsplit" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "workout"."workoutplans" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "workout"."workoutplan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text DEFAULT 'My Workout' NOT NULL,
	"numberofsplits" bigint DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"level" text DEFAULT 'Beginner' NOT NULL,
	"user_id" uuid NOT NULL,
	"trainer_id" uuid,
	"is_active" boolean DEFAULT true NOT NULL,
	"updated_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc') NOT NULL,
	CONSTRAINT "workoutplan_pkey" PRIMARY KEY("id")
);
--> statement-breakpoint
ALTER TABLE "workout"."workoutplans" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "workout"."workoutsplits" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "workout"."workoutsplits_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"workout_id" bigint NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"muscle_group" text,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "workoutsplits_pkey" PRIMARY KEY("id"),
	CONSTRAINT "uq_workoutsplits_plan_name" UNIQUE("workout_id","name")
);
--> statement-breakpoint
ALTER TABLE "workout"."workoutsplits" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "identity"."oauth_accounts" ADD CONSTRAINT "oauth_accounts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "messages"."messages" ADD CONSTRAINT "messages_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "identity"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "messages"."messages" ADD CONSTRAINT "messages_receiver_id_fkey" FOREIGN KEY ("receiver_id") REFERENCES "identity"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "reminders"."user_reminder_settings" ADD CONSTRAINT "user_reminder_settings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reminders"."user_split_information" ADD CONSTRAINT "user_split_information_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reminders"."user_split_information" ADD CONSTRAINT "user_split_information_split_id_fkey" FOREIGN KEY ("split_id") REFERENCES "workout"."workoutsplits"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracking"."aerobictracking" ADD CONSTRAINT "aerobictracking_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "tracking"."exercisetracking" ADD CONSTRAINT "exercisetracking_exercisetosplit_id_fkey" FOREIGN KEY ("exercisetosplit_id") REFERENCES "workout"."exercisetoworkoutsplit"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "tracking"."exercisetracking" ADD CONSTRAINT "exercisetracking_workout_summary_id_fkey" FOREIGN KEY ("workout_summary_id") REFERENCES "tracking"."workout_summary"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "tracking"."workout_summary" ADD CONSTRAINT "workout_summary_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracking"."workout_summary" ADD CONSTRAINT "workout_summary_workoutsplit_id_fkey" FOREIGN KEY ("workoutsplit_id") REFERENCES "workout"."workoutsplits"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "workout"."exercisetoworkoutsplit" ADD CONSTRAINT "ExerciseToWorkoutsplit_exercise_id_fkey" FOREIGN KEY ("exercise_id") REFERENCES "workout"."exercises"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "workout"."exercisetoworkoutsplit" ADD CONSTRAINT "ExerciseToWorkoutsplit_workoutsplit_id_fkey" FOREIGN KEY ("workoutsplit_id") REFERENCES "workout"."workoutsplits"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "workout"."workoutplans" ADD CONSTRAINT "workoutplans_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "workout"."workoutplans" ADD CONSTRAINT "workoutplans_trainer_id_fkey" FOREIGN KEY ("trainer_id") REFERENCES "identity"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "workout"."workoutsplits" ADD CONSTRAINT "workoutsplits_workout_id_fkey" FOREIGN KEY ("workout_id") REFERENCES "workout"."workoutplans"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE UNIQUE INDEX "users_email_ci_unique" ON "identity"."users" USING btree (lower(trim(both from "email"))) WHERE "identity"."users"."email" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "users_username_ci_unique" ON "identity"."users" USING btree (lower(trim(both from "username"))) WHERE "identity"."users"."username" is not null;--> statement-breakpoint
CREATE INDEX "messages_receiver_id_idx" ON "messages"."messages" USING btree ("receiver_id");--> statement-breakpoint
CREATE INDEX "user_split_information_confidence_idx" ON "reminders"."user_split_information" USING btree ("preferred_weekday","confidence") WHERE "reminders"."user_split_information"."confidence" >= 0.60;--> statement-breakpoint
CREATE INDEX "user_split_information_user_weekday_idx" ON "reminders"."user_split_information" USING btree ("user_id","preferred_weekday") WHERE "reminders"."user_split_information"."preferred_weekday" is not null;--> statement-breakpoint
CREATE INDEX "aerobictracking_user_id_workout_time_utc_idx" ON "tracking"."aerobictracking" USING btree ("user_id","workout_time_utc" DESC NULLS FIRST);--> statement-breakpoint
CREATE INDEX "exercisetracking_workout_summary_id_idx" ON "tracking"."exercisetracking" USING btree ("workout_summary_id");--> statement-breakpoint
CREATE INDEX "workout_summary_start_date_idx" ON "tracking"."workout_summary" USING btree ((("workout_start_utc" at time zone 'UTC')::date));--> statement-breakpoint
CREATE INDEX "workout_summary_user_start_utc_idx" ON "tracking"."workout_summary" USING btree ("user_id","workout_start_utc" DESC NULLS FIRST);--> statement-breakpoint
CREATE UNIQUE INDEX "exercises_name_unique" ON "workout"."exercises" USING btree ("name");--> statement-breakpoint
CREATE INDEX "exercisetoworkoutsplit_active_idx" ON "workout"."exercisetoworkoutsplit" USING btree ("workoutsplit_id","order_index") WHERE "workout"."exercisetoworkoutsplit"."is_active" = true;--> statement-breakpoint
CREATE INDEX "exercisetoworkoutsplit_workoutsplit_id_order_index_idx" ON "workout"."exercisetoworkoutsplit" USING btree ("workoutsplit_id","order_index");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_workoutplans_active_user" ON "workout"."workoutplans" USING btree ("user_id") WHERE "workout"."workoutplans"."is_active";--> statement-breakpoint
CREATE INDEX "workoutsplits_workout_id_idx" ON "workout"."workoutsplits" USING btree ("workout_id");--> statement-breakpoint
CREATE VIEW "analytics"."v_exercisetracking_expanded" WITH (security_invoker = true) AS (
    SELECT et.id,
      et.exercisetosplit_id,
      et.weight,
      et.reps,
      ews.exercise_id,
      wsumm.workoutsplit_id,
      ws.name AS splitname,
      ex.name AS exercise,
      et.notes,
      et.workout_summary_id,
      wsumm.workout_start_utc,
      wsumm.workout_end_utc
    FROM tracking.exercisetracking et
    LEFT JOIN tracking.workout_summary wsumm ON wsumm.id = et.workout_summary_id
    LEFT JOIN workout.exercisetoworkoutsplit ews ON ews.id = et.exercisetosplit_id
    LEFT JOIN workout.workoutsplits ws ON ws.id = wsumm.workoutsplit_id
    LEFT JOIN workout.exercises ex ON ex.id = ews.exercise_id
  );--> statement-breakpoint
CREATE VIEW "analytics"."v_exercisetracking_set_simple" WITH (security_invoker = true) AS (
    SELECT et.id,
      et.exercisetosplit_id,
      et.exercise_id,
      et.exercise,
      s.weight,
      s.reps,
      et.workout_summary_id,
      et.workout_start_utc,
      et.workout_end_utc
    FROM analytics.v_exercisetracking_expanded et
    CROSS JOIN LATERAL UNNEST(et.weight, et.reps) s(weight, reps)
  );--> statement-breakpoint
CREATE VIEW "analytics"."v_prs" WITH (security_invoker = true) AS (
    SELECT DISTINCT ON (s.exercise_id)
      s.id,
      s.exercisetosplit_id,
      s.exercise_id,
      s.exercise,
      s.weight,
      s.reps,
      s.workout_summary_id,
      s.workout_start_utc,
      s.workout_end_utc
    FROM analytics.v_exercisetracking_set_simple s
    WHERE s.weight IS NOT NULL AND s.reps IS NOT NULL
    ORDER BY s.exercise_id, s.weight DESC, s.reps DESC, s.workout_start_utc DESC, s.id DESC
  );--> statement-breakpoint
CREATE VIEW "workout"."v_exercisetoworkoutsplit_expanded" WITH (security_invoker = true) AS (
    SELECT ews.id,
      ews.workoutsplit_id,
      ws.workout_id,
      ews.exercise_id,
      ex.name AS exercise,
      ws.name AS workoutsplit,
      ews.sets,
      ews.order_index,
      ews.created_at,
      ews.is_active
    FROM workout.exercisetoworkoutsplit ews
    JOIN workout.workoutsplits ws ON ws.id = ews.workoutsplit_id
    JOIN workout.exercises ex ON ex.id = ews.exercise_id
  );--> statement-breakpoint
CREATE POLICY "Enable read access for auth users on oauth_accounts" ON "identity"."oauth_accounts" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("identity"."current_user_id"() = "identity"."oauth_accounts"."user_id");--> statement-breakpoint
CREATE POLICY "Enable insert for auth users on oauth_accounts" ON "identity"."oauth_accounts" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("identity"."current_user_id"() = "identity"."oauth_accounts"."user_id");--> statement-breakpoint
CREATE POLICY "Enable update for auth users on oauth_accounts" ON "identity"."oauth_accounts" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("identity"."current_user_id"() = "identity"."oauth_accounts"."user_id") WITH CHECK ("identity"."current_user_id"() = "identity"."oauth_accounts"."user_id");--> statement-breakpoint
CREATE POLICY "Enable delete for auth users on oauth_accounts" ON "identity"."oauth_accounts" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("identity"."current_user_id"() = "identity"."oauth_accounts"."user_id");--> statement-breakpoint
CREATE POLICY "Enable read access for auth users on own profile" ON "identity"."users" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("identity"."current_user_id"() = "identity"."users"."id");--> statement-breakpoint
CREATE POLICY "Allow user to view senders in their messages" ON "identity"."users" AS PERMISSIVE FOR SELECT TO "authenticated" USING (exists (select 1 from "messages"."messages" m where m."sender_id" = "identity"."users"."id" and m."receiver_id" = "identity"."current_user_id"()));--> statement-breakpoint
CREATE POLICY "Enable insert for auth users on own profile" ON "identity"."users" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("identity"."current_user_id"() = "identity"."users"."id");--> statement-breakpoint
CREATE POLICY "Enable insert for public users on own profile" ON "identity"."users" AS PERMISSIVE FOR INSERT TO public WITH CHECK ("identity"."current_user_id"() = "identity"."users"."id");--> statement-breakpoint
CREATE POLICY "Enable update for auth users on own profile" ON "identity"."users" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("identity"."current_user_id"() = "identity"."users"."id") WITH CHECK ("identity"."current_user_id"() = "identity"."users"."id");--> statement-breakpoint
CREATE POLICY "Enable delete for auth users on own profile" ON "identity"."users" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("identity"."current_user_id"() = "identity"."users"."id");--> statement-breakpoint
CREATE POLICY "Enable read access for auth users on messages" ON "messages"."messages" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("identity"."current_user_id"() = "messages"."messages"."sender_id" or "identity"."current_user_id"() = "messages"."messages"."receiver_id");--> statement-breakpoint
CREATE POLICY "Enable insert for auth users on messages" ON "messages"."messages" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("identity"."current_user_id"() = "messages"."messages"."sender_id" or "messages"."messages"."sender_id" = '8dedd0e0-8c25-4c84-a05b-4ae5f5c48f3a'::uuid);--> statement-breakpoint
CREATE POLICY "Enable update for auth users on messages" ON "messages"."messages" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("identity"."current_user_id"() = "messages"."messages"."sender_id" or "identity"."current_user_id"() = "messages"."messages"."receiver_id") WITH CHECK ("identity"."current_user_id"() = "messages"."messages"."sender_id" or "identity"."current_user_id"() = "messages"."messages"."receiver_id");--> statement-breakpoint
CREATE POLICY "Enable delete for auth users on messages" ON "messages"."messages" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("identity"."current_user_id"() = "messages"."messages"."sender_id" or "identity"."current_user_id"() = "messages"."messages"."receiver_id");--> statement-breakpoint
CREATE POLICY "auth can SELECT own reminder settings" ON "reminders"."user_reminder_settings" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("identity"."current_user_id"() = "reminders"."user_reminder_settings"."user_id");--> statement-breakpoint
CREATE POLICY "auth can INSERT own reminder settings" ON "reminders"."user_reminder_settings" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("identity"."current_user_id"() = "reminders"."user_reminder_settings"."user_id");--> statement-breakpoint
CREATE POLICY "auth can UPDATE own reminder settings" ON "reminders"."user_reminder_settings" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("identity"."current_user_id"() = "reminders"."user_reminder_settings"."user_id") WITH CHECK ("identity"."current_user_id"() = "reminders"."user_reminder_settings"."user_id");--> statement-breakpoint
CREATE POLICY "Allow authenticated users to update their own reminder settings" ON "reminders"."user_reminder_settings" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("identity"."current_user_id"() = "reminders"."user_reminder_settings"."user_id");--> statement-breakpoint
CREATE POLICY "Enable read access for auth users on aerobictracking" ON "tracking"."aerobictracking" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("identity"."current_user_id"() = "tracking"."aerobictracking"."user_id");--> statement-breakpoint
CREATE POLICY "Enable insert for auth users on aerobictracking" ON "tracking"."aerobictracking" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("identity"."current_user_id"() = "tracking"."aerobictracking"."user_id");--> statement-breakpoint
CREATE POLICY "Enable update for auth users on aerobictracking" ON "tracking"."aerobictracking" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("identity"."current_user_id"() = "tracking"."aerobictracking"."user_id") WITH CHECK ("identity"."current_user_id"() = "tracking"."aerobictracking"."user_id");--> statement-breakpoint
CREATE POLICY "Enable delete for auth users on aerobictracking" ON "tracking"."aerobictracking" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("identity"."current_user_id"() = "tracking"."aerobictracking"."user_id");--> statement-breakpoint
CREATE POLICY "exercisetracking_select_by_summary_owner" ON "tracking"."exercisetracking" AS PERMISSIVE FOR SELECT TO "authenticated" USING (exists (select 1 from "tracking"."workout_summary" ws where ws."id" = "tracking"."exercisetracking"."workout_summary_id" and ws."user_id" = "identity"."current_user_id"()));--> statement-breakpoint
CREATE POLICY "exercisetracking_insert_by_summary_owner" ON "tracking"."exercisetracking" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (exists (select 1 from "tracking"."workout_summary" ws where ws."id" = "tracking"."exercisetracking"."workout_summary_id" and ws."user_id" = "identity"."current_user_id"()));--> statement-breakpoint
CREATE POLICY "exercisetracking_update_by_summary_owner" ON "tracking"."exercisetracking" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (exists (select 1 from "tracking"."workout_summary" ws where ws."id" = "tracking"."exercisetracking"."workout_summary_id" and ws."user_id" = "identity"."current_user_id"())) WITH CHECK (exists (select 1 from "tracking"."workout_summary" ws where ws."id" = "tracking"."exercisetracking"."workout_summary_id" and ws."user_id" = "identity"."current_user_id"()));--> statement-breakpoint
CREATE POLICY "exercisetracking_delete_by_summary_owner" ON "tracking"."exercisetracking" AS PERMISSIVE FOR DELETE TO "authenticated" USING (exists (select 1 from "tracking"."workout_summary" ws where ws."id" = "tracking"."exercisetracking"."workout_summary_id" and ws."user_id" = "identity"."current_user_id"()));--> statement-breakpoint
CREATE POLICY "users can read their workout summaries" ON "tracking"."workout_summary" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("tracking"."workout_summary"."user_id" = "identity"."current_user_id"());--> statement-breakpoint
CREATE POLICY "users can insert their workout summaries" ON "tracking"."workout_summary" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("tracking"."workout_summary"."user_id" = "identity"."current_user_id"());--> statement-breakpoint
CREATE POLICY "users can update their workout summaries" ON "tracking"."workout_summary" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("tracking"."workout_summary"."user_id" = "identity"."current_user_id"()) WITH CHECK ("tracking"."workout_summary"."user_id" = "identity"."current_user_id"());--> statement-breakpoint
CREATE POLICY "users can delete their workout summaries" ON "tracking"."workout_summary" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("tracking"."workout_summary"."user_id" = "identity"."current_user_id"());--> statement-breakpoint
CREATE POLICY "Allow all authenticated users to read exercises" ON "workout"."exercises" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "Enable read access for auth users on exercisetoworkoutsplit" ON "workout"."exercisetoworkoutsplit" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("identity"."current_user_id"() = (select wp."user_id" from "workout"."workoutplans" wp join "workout"."workoutsplits" ws on ws."workout_id" = wp."id" where ws."id" = "workout"."exercisetoworkoutsplit"."workoutsplit_id"));--> statement-breakpoint
CREATE POLICY "Enable insert for auth users on exercisetoworkoutsplit" ON "workout"."exercisetoworkoutsplit" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("identity"."current_user_id"() = (select wp."user_id" from "workout"."workoutplans" wp join "workout"."workoutsplits" ws on ws."workout_id" = wp."id" where ws."id" = "workout"."exercisetoworkoutsplit"."workoutsplit_id"));--> statement-breakpoint
CREATE POLICY "Enable update for auth users on exercisetoworkoutsplit" ON "workout"."exercisetoworkoutsplit" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("identity"."current_user_id"() = (select wp."user_id" from "workout"."workoutplans" wp join "workout"."workoutsplits" ws on ws."workout_id" = wp."id" where ws."id" = "workout"."exercisetoworkoutsplit"."workoutsplit_id")) WITH CHECK ("identity"."current_user_id"() = (select wp."user_id" from "workout"."workoutplans" wp join "workout"."workoutsplits" ws on ws."workout_id" = wp."id" where ws."id" = "workout"."exercisetoworkoutsplit"."workoutsplit_id"));--> statement-breakpoint
CREATE POLICY "Enable delete for auth users on exercisetoworkoutsplit" ON "workout"."exercisetoworkoutsplit" AS PERMISSIVE FOR DELETE TO "authenticated" USING (exists (select 1 from "workout"."workoutsplits" ws join "workout"."workoutplans" wp on wp."id" = ws."workout_id" where ws."id" = "workout"."exercisetoworkoutsplit"."workoutsplit_id" and wp."user_id" = "identity"."current_user_id"()));--> statement-breakpoint
CREATE POLICY "Enable read access for auth users on workoutplans" ON "workout"."workoutplans" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("identity"."current_user_id"() = "workout"."workoutplans"."user_id");--> statement-breakpoint
CREATE POLICY "Enable insert for auth users on workoutplans" ON "workout"."workoutplans" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("identity"."current_user_id"() = "workout"."workoutplans"."user_id");--> statement-breakpoint
CREATE POLICY "Enable update for auth users on workoutplans" ON "workout"."workoutplans" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("identity"."current_user_id"() = "workout"."workoutplans"."user_id") WITH CHECK ("identity"."current_user_id"() = "workout"."workoutplans"."user_id");--> statement-breakpoint
CREATE POLICY "Enable delete for auth users on workoutplans" ON "workout"."workoutplans" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("identity"."current_user_id"() = "workout"."workoutplans"."user_id");--> statement-breakpoint
CREATE POLICY "Enable read access for auth users on workoutsplits" ON "workout"."workoutsplits" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("identity"."current_user_id"() = (select wp."user_id" from "workout"."workoutplans" wp where wp."id" = "workout"."workoutsplits"."workout_id"));--> statement-breakpoint
CREATE POLICY "Enable insert for auth users on workoutsplits" ON "workout"."workoutsplits" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("identity"."current_user_id"() = (select wp."user_id" from "workout"."workoutplans" wp where wp."id" = "workout"."workoutsplits"."workout_id"));--> statement-breakpoint
CREATE POLICY "Enable update for auth users on workoutsplits" ON "workout"."workoutsplits" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("identity"."current_user_id"() = (select wp."user_id" from "workout"."workoutplans" wp where wp."id" = "workout"."workoutsplits"."workout_id")) WITH CHECK ("identity"."current_user_id"() = (select wp."user_id" from "workout"."workoutplans" wp where wp."id" = "workout"."workoutsplits"."workout_id"));--> statement-breakpoint
CREATE POLICY "Enable delete for auth users on workoutsplits" ON "workout"."workoutsplits" AS PERMISSIVE FOR DELETE TO "authenticated" USING (exists (select 1 from "workout"."workoutplans" wp where wp."id" = "workout"."workoutsplits"."workout_id" and wp."user_id" = "identity"."current_user_id"()));--> statement-breakpoint

-- Drizzle Kit does not currently model replica identity, routines, triggers,
-- cron jobs, comments, object grants, or default privileges. They complete
-- the baseline below using the final state of the legacy migration history.
ALTER TABLE "identity"."users" REPLICA IDENTITY FULL;--> statement-breakpoint
ALTER TABLE "messages"."messages" REPLICA IDENTITY FULL;--> statement-breakpoint
-- The legacy history added this redundant unique constraint after the primary key.
-- Keeping it separate prevents PostgreSQL from folding both inline constraints together.
ALTER TABLE "identity"."users" ADD CONSTRAINT "users_id_key1" UNIQUE ("id");--> statement-breakpoint

CREATE SEQUENCE "reminders"."user_split_information_id_seq"
  AS bigint START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;--> statement-breakpoint

CREATE OR REPLACE FUNCTION "workout"."update_muscle_group_trigger_function"()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE workout.workoutsplits AS ws
  SET muscle_group = (
    SELECT STRING_AGG(t.targetmuscle || ' (' || t.specifics || ')', ', ')
    FROM (
      SELECT e.targetmuscle,
        STRING_AGG(DISTINCT e.specifictargetmuscle, ', ' ORDER BY e.specifictargetmuscle) AS specifics
      FROM workout.exercisetoworkoutsplit AS ew
      JOIN workout.exercises AS e ON e.id = ew.exercise_id
      WHERE ew.workoutsplit_id = COALESCE(NEW.workoutsplit_id, OLD.workoutsplit_id)
        AND ew.is_active = TRUE
        AND e.targetmuscle IS NOT NULL
      GROUP BY e.targetmuscle
    ) AS t
  )
  WHERE ws.id = COALESCE(NEW.workoutsplit_id, OLD.workoutsplit_id);
  RETURN COALESCE(NEW, OLD);
END;
$$;--> statement-breakpoint

CREATE TRIGGER "update_muscle_group_trigger"
AFTER INSERT OR DELETE OR UPDATE ON "workout"."exercisetoworkoutsplit"
FOR EACH ROW
EXECUTE FUNCTION "workout"."update_muscle_group_trigger_function"();--> statement-breakpoint

CREATE OR REPLACE FUNCTION "tracking"."housekeeping_compact_old_workouts"()
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path TO ''
AS $$
WITH today_utc AS (
  SELECT (now() AT TIME ZONE 'UTC')::date AS d
), days AS (
  SELECT ws.user_id, (ws.workout_start_utc AT TIME ZONE 'UTC')::date AS d
  FROM tracking.exercisetracking et
  JOIN tracking.workout_summary ws ON ws.id = et.workout_summary_id
  GROUP BY ws.user_id, d
), ranked_days AS (
  SELECT user_id, d, ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY d DESC) AS day_rank
  FROM days
), old_days AS (
  SELECT rd.user_id, rd.d
  FROM ranked_days rd
  CROSS JOIN today_utc t
  WHERE rd.day_rank > 35 AND rd.d < (t.d - INTERVAL '45 days')
)
DELETE FROM tracking.exercisetracking et
USING tracking.workout_summary ws, old_days od
WHERE et.workout_summary_id = ws.id
  AND ws.user_id = od.user_id
  AND (ws.workout_start_utc AT TIME ZONE 'UTC')::date = od.d;
$$;--> statement-breakpoint

CREATE OR REPLACE FUNCTION "reminders"."refresh_user_split_information"()
RETURNS void
LANGUAGE sql
AS $$
WITH recent_workouts AS (
  SELECT ws.user_id, ws.workoutsplit_id AS split_id, ws.workout_end_utc, ws.workout_start_utc
  FROM tracking.exercisetracking et
  JOIN tracking.workout_summary ws ON ws.id = et.workout_summary_id
  WHERE ws.workout_start_utc >= timezone('UTC', now()) - INTERVAL '21 days'
    AND ws.workoutsplit_id IS NOT NULL
), weekday_counts AS (
  SELECT rw.user_id, rw.split_id,
    EXTRACT(DOW FROM rw.workout_start_utc at time zone urs.timezone) AS weekday,
    COUNT(*) AS cnt,
    ROW_NUMBER() OVER (PARTITION BY rw.user_id, rw.split_id ORDER BY COUNT(*) DESC) AS rn
  FROM recent_workouts rw
  JOIN reminders.user_reminder_settings urs ON urs.user_id = rw.user_id
  GROUP BY rw.user_id, rw.split_id, EXTRACT(DOW FROM rw.workout_start_utc at time zone urs.timezone)
), filtered AS (
  SELECT rw.user_id, rw.split_id, rw.workout_start_utc AS adjusted_time_utc,
    EXTRACT(DOW FROM rw.workout_start_utc) AS weekday
  FROM recent_workouts rw
  JOIN weekday_counts wc ON wc.user_id = rw.user_id AND wc.split_id = rw.split_id
    AND wc.weekday = EXTRACT(DOW FROM rw.workout_start_utc) AND wc.rn = 1
), aggregated AS (
  SELECT f.user_id, f.split_id, wc.weekday AS preferred_weekday, COUNT(*) AS total_cnt,
    FLOOR(AVG((EXTRACT(EPOCH FROM f.adjusted_time_utc)) % 86400))::int AS avg_seconds_in_day
  FROM filtered f
  JOIN weekday_counts wc ON wc.user_id = f.user_id AND wc.split_id = f.split_id
    AND wc.weekday = f.weekday AND wc.rn = 1
  GROUP BY f.user_id, f.split_id, wc.weekday
), finalized AS (
  SELECT a.user_id, a.split_id,
    DATE_TRUNC('day', timezone('UTC', now())) + make_interval(secs => a.avg_seconds_in_day) AS estimated_time_utc,
    a.preferred_weekday, a.total_cnt
  FROM aggregated a
)
INSERT INTO reminders.user_split_information
  (user_id, split_id, estimated_time_utc, confidence, last_computed_at, preferred_weekday)
SELECT f.user_id, f.split_id, f.estimated_time_utc,
  CASE WHEN f.total_cnt >= 3 THEN 1.00 WHEN f.total_cnt = 2 THEN 0.60 ELSE 0.30 END,
  timezone('UTC', now()), f.preferred_weekday
FROM finalized f
ON CONFLICT (user_id, split_id) DO UPDATE
SET estimated_time_utc = EXCLUDED.estimated_time_utc,
  confidence = EXCLUDED.confidence,
  last_computed_at = EXCLUDED.last_computed_at,
  preferred_weekday = EXCLUDED.preferred_weekday;
$$;--> statement-breakpoint

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'cron') THEN
    PERFORM cron.schedule('compact_old_workouts_daily', '10 0 * * *',
      'SELECT tracking.housekeeping_compact_old_workouts();');
    PERFORM cron.schedule('refresh-user-split-information-daily', '0 2 * * *',
      'SELECT reminders.refresh_user_split_information();');
  END IF;
END
$$;--> statement-breakpoint

COMMENT ON SCHEMA "identity" IS 'Application-owned identity and account data';
COMMENT ON SCHEMA "workout" IS 'Workout plans, split structure, and exercise catalog data';
COMMENT ON SCHEMA "tracking" IS 'Completed workout, exercise tracking, and aerobic tracking data';
COMMENT ON SCHEMA "reminders" IS 'Reminder preferences and computed split reminder metadata';
COMMENT ON SCHEMA "messages" IS 'User and system message inbox data';
COMMENT ON SCHEMA "analytics" IS 'Reporting and analytics views';
COMMENT ON TABLE "tracking"."aerobictracking" IS 'All aerobic trackings';
COMMENT ON TABLE "workout"."exercises" IS 'All exercises';
COMMENT ON TABLE "tracking"."exercisetracking" IS 'Exercise tracking';
COMMENT ON TABLE "messages"."messages" IS 'All messages inside app - user to user, app to user etc..';
COMMENT ON TABLE "identity"."oauth_accounts" IS 'All oauth accounts information';
COMMENT ON COLUMN "identity"."oauth_accounts"."linked_at" IS 'When account was first created/linked to oauth';
COMMENT ON COLUMN "identity"."oauth_accounts"."missing_fields" IS 'Missing fields for user profile';
COMMENT ON TABLE "identity"."users" IS 'All registered users';
COMMENT ON COLUMN "identity"."users"."token_version" IS 'Token version for two-devices validation';
COMMENT ON COLUMN "identity"."users"."is_verified" IS 'Email validation';
COMMENT ON COLUMN "identity"."users"."auth_provider" IS 'Auth provider (Apple, Google, App)';
COMMENT ON TABLE "workout"."workoutsplits" IS 'All workout splits';
COMMENT ON TABLE "workout"."workoutplans" IS 'All workout plans';
COMMENT ON COLUMN "workout"."workoutplans"."level" IS 'Level of the workout';--> statement-breakpoint

GRANT USAGE ON SCHEMA "public" TO "anon", "authenticated", "service_role", "app_user";
GRANT USAGE ON SCHEMA "identity", "workout", "tracking", "reminders", "analytics", "messages" TO "authenticated", "service_role", "app_user";
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON ALL TABLES IN SCHEMA "identity", "workout", "tracking", "reminders", "analytics", "messages" TO "anon", "authenticated", "service_role", "app_user";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "identity", "workout", "tracking", "reminders", "analytics", "messages" TO "anon", "authenticated", "service_role";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "identity", "workout", "tracking", "reminders", "analytics", "messages" TO "app_user";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA "identity", "workout", "tracking", "reminders", "analytics", "messages" TO "anon", "authenticated", "service_role";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "identity", "workout", "tracking", "reminders", "analytics", "messages" TO "app_user";--> statement-breakpoint

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "identity", "workout", "tracking", "reminders", "analytics", "messages" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "identity", "workout", "tracking", "reminders", "analytics", "messages" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "identity", "workout", "tracking", "reminders", "analytics", "messages" GRANT ALL ON FUNCTIONS TO "authenticated";
